### ISSUE TITLE
·[DataCap Application]The International Genome Sample Resource

### ISSUE THREAD

**Issue by yse88483** [NewHuoPool/NewHuoPoolPathway#1]
### Version

1

### DataCap Applicant

DATADAO

### Project ID

DATADAO-03

### Data Owner Name

The International Genome Sample Resource

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.internationalgenome.org/

### Social Media Handle

https://www.internationalgenome.org/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

384TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

250TiB

### On-chain address for first allocation

f1kzg6jctjv7ymsidesasfp6lldmxa5nje4z4mxqi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
DATADAO is built upon technical expertise and utilizes proprietary programs and advanced tools to provide customized car data packaging services to clients. Our team boasts extensive experience and proficiency in utilizing cutting-edge tools such as go-graphsplit and singularity to ensure efficient and accurate data packaging. Our service process encompasses the following key points:

Technical Expertise: Our team possesses rich technical expertise in utilizing advanced tools. By leveraging tools like go-graphsplit and singularity, we ensure the efficiency and accuracy of data packaging. These tools aid us in processing and packaging client-provided data to meet the storage requirements of the Filecoin network.

Data Processing Flow: We employ proprietary programs to segment, package, and compress client-provided data, ultimately generating ZIP files ranging from 28-32GB in size to align with the storage requirements of the Filecoin network. Through these services, we effectively assist clients in processing and preparing data for storage and usage on the Filecoin network.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The 1000 Genomes Project created a catalogue of common human genetic variation, using openly consented samples from people who declared themselves to be healthy. The reference data resources generated by the project remain heavily used by the biomedical science community.

The International Genome Sample Resource (IGSR) maintains and shares the human genetic variation resources built by the 1000 Genomes Project. We also update the resources to the current reference assembly, add new data sets generated from the 1000 Genomes Project samples and add data from projects working with other openly consented samples.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://www.internationalgenome.org/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03086293 | HK
f02824216 |ZheJiang
f02951213 | Singapore
f03068013 |HK
f02200472| SiChuang
f03035686 | JiangXi
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by NewHuoPool** [comment]
Hi@yse88483 , thanks for submitting your application here.
I've received your [due diligence form](https://github.com/NewHuoPool/DataCap-Application/issues/2) .
Regarding the SP partnership plan you shared, we suggest that clients utilize distributed storage as much as possible. What are your plans regarding this?

**Comment by yse88483** [comment]
Hello, thanks for your reply, kindhearted person!
We cooperate with 8 SPs and will expand to 15 SPs in the next 15 days, distributed in Asia, China and the Americas.
Looking forward to getting your help.
Thanks you!

**Comment by NewHuoPool** [comment]
checker:manualTrigger

**Comment by NewHuoPool** [comment]
@yse88483 
SPs taking deals:
f02824216 | Shanghai, CN
f03086293 | Hong Kong, HK
SPs don't match. Could you explain, please?

**Comment by yse88483** [comment]
Dear allocator, thanks for your question. This is the latest situation of our cooperative SPs. Since some SPs' FIL has been used up, there have been changes. This is the latest data, please check it.
We have modified the application form and we strictly follow the SP listed. If there are any changes, we will inform you in advance. Thank you.

**Comment by NewHuoPool** [comment]
checker:manualTrigger

**Comment by NewHuoPool** [comment]
Used the lotus -peerid command to query three nodes successfully; all systems are functional. 
This batch is authorized for the Second Allocation, accounting for 15%.

**Comment by NewHuoPool** [comment]
checker:manualTrigger

**Comment by NewHuoPool** [comment]
Used the lotus -peerid command to query all nodes successfully.
This batch is authorized for the 3rd Allocation, accounting for 30%.

**Comment by NewHuoPool** [comment]
checker:manualTrigger

**Comment by NewHuoPool** [comment]
@yse88483 
During the course of the project, I'd like to remind you of the following:
1.Please cooperate in keeping your SP information up to date, including SP ID, region, and organization. If this isn't the case, kindly provide a reasonable explanation. This will ensure that our information remains synchronized at all times.
2.Is the SPs experiencing any difficulties with Spark retrieval? I've noticed one node achieving an 80% Spark retrieval rate, which is a promising start. If necessary, please refer to this [https://filspark.com/troubleshooting-miner-score#block-7e10034eb61e417b9a69383b1e15018f](https://filspark.com/troubleshooting-miner-score#block-7e10034eb61e417b9a69383b1e15018f) for configuration guidance.

**Comment by NewHuoPool** [comment]
checker:manualTrigger

**Comment by NewHuoPool** [comment]
@yse88483 Any updates? If we don't receive any responses within 5 days, we'll close this application.
